mkdir -p .github/workflows
cat > .github/workflows/blb-weekly.yml <<'YML'
name: BLB weekly

on:
  schedule:
    - cron: '20 15 * * 1'  # 15:20 UTC = JST 00:20 火曜
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: python -m pip install -U -r requirements.txt
      - name: Run BLB
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          HTTPS_ONLY: '1'
          FREE_INCLUDE_COM_IN_JA: '1'
          TOPK_PER_QUERY: '10'
          MAX_QUERIES: '200'
          PER_DOMAIN_MAX_PER_QUERY: '1'
          REQUEST_TIMEOUT: '12'
        run: |
          python -m src.main --discover --scan --suggest --time-budget-min 180
YML

git add .github/workflows/blb-weekly.yml
git commit -m "ci: weekly BLB run via GitHub Actions (UTC schedule)"
git push
