name: broken-link-builder
on:
  workflow_dispatch: {}
  schedule:
    - cron: "20 15 * * 1" # 毎週月曜 24:20 JST

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -r requirements.txt
      - name: Run
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          VERBOSE: "1"
          ROWS_LIMIT: "0"
          FLUSH_EVERY: "5"
        run: python -u -m src.main
